/* global XLSX */
const $=id=>document.getElementById(id),fmt=new Intl.NumberFormat('en-GB',{maximumFractionDigits:1}),money=new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP',maximumFractionDigits:0});
const groups=['Unit Savings','Monthly Unit Progress','Hours Worked Breakdown','Outlook','Agency vs Permanent','Budget'];
let rows=[],active=groups[0],filters={branch:'All branches',year:'latest',month:'all'};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const val=v=>typeof v==='number'&&Number.isFinite(v)?v:null;
function normalise(r){return{year:+r.Year,month:+r.Month,branch:String(r.Branch||'Unassigned').trim(),group:String(r.Group||'').trim(),measure:String(r.Measure||'').trim(),value:+r.Value,target:r.Target===''||r.Target==null?null:+r.Target,unit:String(r.Unit||'number'),updated:String(r.UpdatedAt||'')}}
function validate(a){const needed=['Year','Month','Branch','Group','Measure','Value'],heads=Object.keys(a[0]||{});return needed.filter(x=>!heads.includes(x))}
async function load(file){let raw;if(file.name.endsWith('.json'))raw=JSON.parse(await file.text()).rows||[];else{const wb=XLSX.read(await file.arrayBuffer(),{type:'array',cellDates:true}),sh=wb.Sheets['Dashboard Export'];if(!sh)throw Error('Worksheet “Dashboard Export” was not found.');raw=XLSX.utils.sheet_to_json(sh,{defval:''})}const missing=validate(raw);if(missing.length)throw Error(`Missing columns: ${missing.join(', ')}`);rows=raw.map(normalise).filter(r=>r.year&&r.month&&groups.includes(r.group)&&val(r.value)!==null);if(!rows.length)throw Error('No valid aggregate KPI rows were found.');buildFilters();render();$('status').textContent=`${rows.length} aggregate figures loaded`;const times=rows.map(r=>r.updated).filter(Boolean).sort();$('refreshed').textContent=times.at(-1)||'Not supplied'}
function buildFilters(){const branches=[...new Set(rows.map(r=>r.branch))].sort(),years=[...new Set(rows.map(r=>r.year))].sort((a,b)=>b-a);$('branch').innerHTML='<option>All branches</option>'+branches.map(x=>`<option>${esc(x)}</option>`).join('');$('year').innerHTML='<option value="latest">Latest year</option><option value="all">All years</option>'+years.map(x=>`<option>${x}</option>`).join('');$('month').innerHTML='<option value="all">All months</option>'+Array.from({length:12},(_,i)=>`<option value="${i+1}">${new Date(2026,i).toLocaleString('en-GB',{month:'long'})}</option>`).join('')}
function selected(){const latest=Math.max(0,...rows.map(r=>r.year));return rows.filter(r=>(filters.branch==='All branches'||r.branch===filters.branch)&&(filters.year==='all'||r.year===(filters.year==='latest'?latest:+filters.year))&&(filters.month==='all'||r.month===+filters.month)&&r.group===active)}
function aggregate(a){const m=new Map;for(const r of a){const k=r.measure;if(!m.has(k))m.set(k,{...r,value:0,n:0});const x=m.get(k);x.value+=r.value;x.n++}return[...m.values()].map(r=>({...r,value:r.unit==='percent'?r.value/r.n:r.value}))}
const display=r=>r.unit==='currency'?money.format(r.value):r.unit==='percent'?`${fmt.format(r.value*100)}%`:fmt.format(r.value);
function render(){const a=selected(),metrics=aggregate(a);$('content').innerHTML=!a.length?'<div class="table-card empty">No matching aggregate figures</div>':`<div class="kpis">${metrics.slice(0,4).map(r=>`<article class="card"><span>${esc(r.measure)}</span><strong>${display(r)}</strong><small>${r.target==null?'No target supplied':`Target ${r.unit==='percent'?fmt.format(r.target*100)+'%':fmt.format(r.target)}`}</small></article>`).join('')}</div><div class="grid"><article class="card"><h2>Branch comparison</h2>${branchBars(a)}</article><article class="card"><h2>Measure summary</h2>${metricBars(metrics)}</article></div><article class="table-card"><h2>Monthly detail</h2><table><thead><tr><th>Year</th><th>Month</th><th>Branch</th><th>Measure</th><th class="num">Value</th><th class="num">Target</th></tr></thead><tbody>${a.sort((x,y)=>x.year-y.year||x.month-y.month||x.branch.localeCompare(y.branch)).map(r=>`<tr><td>${r.year}</td><td>${new Date(r.year,r.month-1).toLocaleString('en-GB',{month:'short'})}</td><td>${esc(r.branch)}</td><td>${esc(r.measure)}</td><td class="num">${display(r)}</td><td class="num">${r.target==null?'—':r.unit==='percent'?fmt.format(r.target*100)+'%':fmt.format(r.target)}</td></tr>`).join('')}</tbody></table></article>`;renderChecks()}
function branchBars(a){const first=aggregate(a)[0];if(!first)return'';const m=new Map;for(const r of a.filter(x=>x.measure===first.measure)){const x=m.get(r.branch)||{value:0,n:0};x.value+=r.value;x.n++;m.set(r.branch,x)}return`<small>${esc(first.measure)}</small>`+bars([...m].map(([name,x])=>({name,value:Math.abs(first.unit==='percent'?x.value/x.n:x.value),unit:first.unit})))}function metricBars(a){return bars(a.map(r=>({name:r.measure,value:Math.abs(r.value),unit:r.unit})))}function bars(a){const max=Math.max(1,...a.map(x=>x.value));return a.slice(0,12).map(x=>`<div class="bar"><span>${esc(x.name)}</span><span class="track"><i style="width:${x.value/max*100}%"></i></span><b class="num">${x.unit==='percent'?fmt.format(x.value*100)+'%':fmt.format(x.value)}</b></div>`).join('')}
function renderChecks(){const present=new Set(rows.map(r=>r.group));const checks=[...groups.map(g=>({t:g,ok:present.has(g)})),{t:'No raw customer fields',ok:true},{t:'Refresh timestamp',ok:rows.some(r=>r.updated)}];$('checks').className='checks';$('checks').innerHTML=checks.map(x=>`<span class="check ${x.ok?'':'bad'}">${x.ok?'✓':'!'} ${esc(x.t)}</span>`).join('')}
$('tabs').innerHTML=groups.map((g,i)=>`<button class="${i?'':'active'}" data-g="${g}">${g}</button>`).join('');$('tabs').onclick=e=>{if(!e.target.dataset.g)return;active=e.target.dataset.g;[...$('tabs').children].forEach(b=>b.classList.toggle('active',b===e.target));render()};$('uploadBtn').onclick=()=>$('file').click();$('file').onchange=async e=>{try{await load(e.target.files[0])}catch(err){$('status').textContent=err.message}};for(const id of['branch','year','month'])$(id).onchange=e=>{filters[id]=e.target.value;render()};
buildFilters();renderChecks();render();fetch('./dashboard-data.json',{cache:'no-store'}).then(r=>r.ok?r.json():Promise.reject()).then(d=>{rows=(d.rows||[]).map(normalise).filter(r=>groups.includes(r.group)&&val(r.value)!==null);buildFilters();render();$('status').textContent=rows.length?(d.isTestData?'Test dataset loaded':'Published figures loaded'):'Test mode · no operational data published';const times=rows.map(r=>r.updated).filter(Boolean).sort();$('refreshed').textContent=times.at(-1)||'—'}).catch(()=>{});
