EVALUATE
VAR MaximumYear = YEAR(TODAY()) + IF(MONTH(TODAY()) = 12, 1, 0)
VAR Core =
    SUMMARIZECOLUMNS(
        'DataSet'[rc-date],
        'DataSet'[Removals.r-brch],
        'DataSet'[rc-type],
        'DataSet'[ch-status],
        'DataSet'[Inventory.in-costingdefault],
        'DataSet'[rc-act],
        'Branch - Dimensions'[Location],
        'Branch - Dimensions'[NCat3Name],
        FILTER(
            ALL('DataSet'[rc-date]),
            'DataSet'[rc-date] >= DATE(2026, 1, 1)
                && YEAR('DataSet'[rc-date]) <= MaximumYear
        ),
        TREATAS({"Labour", "Vehicle"}, 'DataSet'[rc-type]),
        FILTER(
            ALL('DataSet'[Removals.r-number]),
            'DataSet'[Removals.r-number] <> "396809"
        ),
        FILTER(
            ALL('Branch - Dimensions'[Location]),
            NOT('Branch - Dimensions'[Location] IN {"AZN", "DAS", "GHO", "OTHER", "QED"})
        ),
        FILTER(
            ALL('Branch - Dimensions'[NCat3Name]),
            'Branch - Dimensions'[NCat3Name] <> "London Logistic City"
        ),
        FILTER(
            ALL('DataSet'[rc-cost-type]),
            NOT(
                'DataSet'[rc-cost-type] IN {
                    "Crew Bus DOffs",
                    "IT Electrician",
                    "IT Technician",
                    "IT Engineer",
                    "IT Server Engineer",
                    "IT Team Leader",
                    "Operations Supervisor",
                    "Project Manager",
                    "Project Manager Life Sciences",
                    "Project Administrator",
                    "Driver (DropOffs)"
                }
            )
        ),
        "Quantity", SUM('DataSet'[Qty-New])
    )
RETURN
    SELECTCOLUMNS(
        Core,
        "Date", 'DataSet'[rc-date],
        "BranchCode", 'DataSet'[Removals.r-brch],
        "UnitType", 'DataSet'[rc-type],
        "Status", 'DataSet'[ch-status],
        "BookedQuantity",
            IF(
                (
                    'DataSet'[rc-date] < TODAY()
                        && 'DataSet'[ch-status] <> "C"
                        && 'DataSet'[ch-status] <> "L"
                        && NOT(ISBLANK('DataSet'[ch-status]))
                        && 'DataSet'[Inventory.in-costingdefault] = "N"
                        && 'DataSet'[rc-act] <> 0
                )
                ||
                (
                    'DataSet'[rc-date] >= TODAY()
                        && 'DataSet'[ch-status] <> "C"
                        && 'DataSet'[ch-status] <> "L"
                        && 'DataSet'[ch-status] <> "P"
                        && NOT(ISBLANK('DataSet'[ch-status]))
                        && 'DataSet'[Inventory.in-costingdefault] = "Y"
                        && 'DataSet'[rc-act] = 0
                ),
                [Quantity],
                0
            ),
        "PendingQuantity",
            IF(
                'DataSet'[rc-date] >= TODAY()
                    && 'DataSet'[ch-status] = "P"
                    && 'DataSet'[Inventory.in-costingdefault] = "Y"
                    && 'DataSet'[rc-act] = 0,
                [Quantity],
                0
            )
    )
